/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Users\apens_000\Downloads\nim-original\lib -o c:\users\apens_000\documents\nimcode\nimdigest\whirlpool\nimcache\stdlib_hashes.o c:\users\apens_000\documents\nimcode\nimdigest\whirlpool\nimcache\stdlib_hashes.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, HEX21HEX26_99009)(NI h, NI val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, HEX21HEX24_99038)(NI h);
N_NIMCALL(NI, hashdata_99066)(void* data, NI size);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, hash_99401)(void* x);
static N_INLINE(NI, hash_99804)(NI x);
static N_INLINE(NI, hash_99814)(NI64 x);
static N_INLINE(NI, hash_99824)(NIM_CHAR x);
N_NIMCALL(NI, hash_99842)(NimStringDesc* x);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, hashignorestyle_99890)(NimStringDesc* x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NI, hashignorecase_99981)(NimStringDesc* x);
static N_INLINE(NI, hash_100068)(NF x);
extern TFrame* frameptr_17042;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

static N_INLINE(NI, HEX21HEX26_99009)(NI h, NI val) {
	NI result;
	nimfr("!&", "hashes.nim")
	result = 0;
	nimln(51, "hashes.nim");
	result = (NI)((NU64)(h) + (NU64)(val));
	nimln(52, "hashes.nim");
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(((NI) 10)))));
	nimln(53, "hashes.nim");
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(((NI) 6))));
	popFrame();
	return result;
}

static N_INLINE(NI, HEX21HEX24_99038)(NI h) {
	NI result;
	nimfr("!$", "hashes.nim")
	result = 0;
	nimln(58, "hashes.nim");
	result = (NI)((NU64)(h) + (NU64)((NI)((NU64)(h) << (NU64)(((NI) 3)))));
	nimln(59, "hashes.nim");
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(((NI) 11))));
	nimln(60, "hashes.nim");
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(((NI) 15)))));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hashdata_99066)(void* data, NI size) {
	NI result;
	NI h;
	NCSTRING p;
	NI i;
	NI s;
	nimfr("hashData", "hashes.nim")
	result = 0;
	nimln(64, "hashes.nim");
	h = ((NI) 0);
	nimln(69, "hashes.nim");
	p = ((NCSTRING) (data));
	nimln(70, "hashes.nim");
	i = ((NI) 0);
	nimln(71, "hashes.nim");
	s = size;
	{
		nimln(72, "hashes.nim");
		while (1) {
			NI TMP145;
			NI TMP146;
			if (!(((NI) 0) < s)) goto LA2;
			nimln(73, "hashes.nim");
			h = HEX21HEX26_99009(h, ((NI) (((NU8)(p[i])))));
			nimln(74, "hashes.nim");
			TMP145 = addInt(i, ((NI) 1));
			i = (NI)(TMP145);
			nimln(75, "hashes.nim");
			TMP146 = subInt(s, ((NI) 1));
			s = (NI)(TMP146);
		} LA2: ;
	}
	nimln(76, "hashes.nim");
	result = HEX21HEX24_99038(h);
	popFrame();
	return result;
}

static N_INLINE(NI, hash_99401)(void* x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(95, "hashes.nim");
	result = (NI)((NU64)(((NI) (x))) >> (NU64)(((NI) 3)));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_99804)(NI x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(107, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NI, hash_99814)(NI64 x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(111, "hashes.nim");
	result = ((NI) (((NI32)(NU32)(NU64)(x))));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_99824)(NIM_CHAR x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(115, "hashes.nim");
	result = ((NI) (((NU8)(x))));
	popFrame();
	return result;
}

N_NIMCALL(NI, hash_99842)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(119, "hashes.nim");
	h = ((NI) 0);
	{
		NI i_99857;
		NI HEX3Atmp_99868;
		NI TMP147;
		NI res_99871;
		i_99857 = 0;
		HEX3Atmp_99868 = 0;
		nimln(120, "hashes.nim");
		TMP147 = subInt((x ? x->Sup.len : 0), ((NI) 1));
		HEX3Atmp_99868 = (NI)(TMP147);
		nimln(1598, "system.nim");
		res_99871 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP148;
				if (!(res_99871 <= HEX3Atmp_99868)) goto LA3;
				nimln(1600, "system.nim");
				i_99857 = res_99871;
				nimln(121, "hashes.nim");
				if ((NU)(i_99857) > (NU)(x->Sup.len)) raiseIndexError();
				h = HEX21HEX26_99009(h, ((NI) (((NU8)(x->data[i_99857])))));
				nimln(1619, "system.nim");
				TMP148 = addInt(res_99871, ((NI) 1));
				res_99871 = (NI)(TMP148);
			} LA3: ;
		}
	}
	nimln(122, "hashes.nim");
	result = HEX21HEX24_99038(h);
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hashignorestyle_99890)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hashIgnoreStyle", "hashes.nim")
	result = 0;
	nimln(126, "hashes.nim");
	h = ((NI) 0);
	{
		NI i_99905;
		NI HEX3Atmp_99956;
		NI TMP149;
		NI res_99959;
		i_99905 = 0;
		HEX3Atmp_99956 = 0;
		nimln(127, "hashes.nim");
		TMP149 = subInt((x ? x->Sup.len : 0), ((NI) 1));
		HEX3Atmp_99956 = (NI)(TMP149);
		nimln(1598, "system.nim");
		res_99959 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP151;
				if (!(res_99959 <= HEX3Atmp_99956)) goto LA3;
				nimln(1600, "system.nim");
				i_99905 = res_99959;
				{
					NIM_CHAR c;
					nimln(128, "hashes.nim");
					if ((NU)(i_99905) > (NU)(x->Sup.len)) raiseIndexError();
					c = x->data[i_99905];
					nimln(129, "hashes.nim");
					{
						if (!((NU8)(c) == (NU8)(95))) goto LA7;
						nimln(130, "hashes.nim");
						goto LA4;
					}
					LA7: ;
					nimln(131, "hashes.nim");
					{
						NI TMP150;
						if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA11;
						nimln(132, "hashes.nim");
						TMP150 = addInt(((NI) (((NU8)(c)))), ((NI) 32));
						c = ((NIM_CHAR) (((NI)chckRange((NI)(TMP150), ((NI) 0), ((NI) 255)))));
					}
					LA11: ;
					nimln(133, "hashes.nim");
					h = HEX21HEX26_99009(h, ((NI) (((NU8)(c)))));
				} LA4: ;
				nimln(1619, "system.nim");
				TMP151 = addInt(res_99959, ((NI) 1));
				res_99959 = (NI)(TMP151);
			} LA3: ;
		}
	}
	nimln(134, "hashes.nim");
	result = HEX21HEX24_99038(h);
	popFrame();
	return result;
}

N_NIMCALL(NI, hashignorecase_99981)(NimStringDesc* x) {
	NI result;
	NI h;
	nimfr("hashIgnoreCase", "hashes.nim")
	result = 0;
	nimln(138, "hashes.nim");
	h = ((NI) 0);
	{
		NI i_99996;
		NI HEX3Atmp_100046;
		NI TMP152;
		NI res_100049;
		i_99996 = 0;
		HEX3Atmp_100046 = 0;
		nimln(139, "hashes.nim");
		TMP152 = subInt((x ? x->Sup.len : 0), ((NI) 1));
		HEX3Atmp_100046 = (NI)(TMP152);
		nimln(1598, "system.nim");
		res_100049 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NIM_CHAR c;
				NI TMP154;
				if (!(res_100049 <= HEX3Atmp_100046)) goto LA3;
				nimln(1600, "system.nim");
				i_99996 = res_100049;
				nimln(140, "hashes.nim");
				if ((NU)(i_99996) > (NU)(x->Sup.len)) raiseIndexError();
				c = x->data[i_99996];
				nimln(141, "hashes.nim");
				{
					NI TMP153;
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA6;
					nimln(142, "hashes.nim");
					TMP153 = addInt(((NI) (((NU8)(c)))), ((NI) 32));
					c = ((NIM_CHAR) (((NI)chckRange((NI)(TMP153), ((NI) 0), ((NI) 255)))));
				}
				LA6: ;
				nimln(143, "hashes.nim");
				h = HEX21HEX26_99009(h, ((NI) (((NU8)(c)))));
				nimln(1619, "system.nim");
				TMP154 = addInt(res_100049, ((NI) 1));
				res_100049 = (NI)(TMP154);
			} LA3: ;
		}
	}
	nimln(144, "hashes.nim");
	result = HEX21HEX24_99038(h);
	popFrame();
	return result;
}

static N_INLINE(NI, hash_100068)(NF x) {
	NI result;
	NF y;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(147, "hashes.nim");
	y = ((NF)(x) + (NF)(1.0000000000000000e+000));
	nimln(148, "hashes.nim");
	result = (*((NI*) ((&y))));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit)(void) {
	nimfr("hashes", "hashes.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit)(void) {
}

