/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Users\apens_000\Downloads\nim-original\lib -o c:\users\apens_000\documents\shimsham\whirlpool\nimcache\stdlib_strutils.o c:\users\apens_000\documents\shimsham\whirlpool\nimcache\stdlib_strutils.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19801)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP245, "0123456789ABCDEF", 16);
extern TFrame* frameptr_17042;

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr("toLower", "strutils.nim")
	result = 0;
	nimln(69, "strutils.nim");
	{
		NI TMP242;
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		nimln(70, "strutils.nim");
		TMP242 = addInt(((NI) (((NU8)(c)))), ((NI) 32));
		result = ((NIM_CHAR) (((NI)chckRange((NI)(TMP242), ((NI) 0), ((NI) 255)))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(72, "strutils.nim");
		result = c;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr("toLower", "strutils.nim")
	result = 0;
	nimln(81, "strutils.nim");
	result = mnewString(((NI)chckRange((s ? s->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i_93091;
		NI HEX3Atmp_93093;
		NI TMP241;
		NI res_93096;
		i_93091 = 0;
		HEX3Atmp_93093 = 0;
		nimln(82, "strutils.nim");
		TMP241 = subInt((s ? s->Sup.len : 0), ((NI) 1));
		HEX3Atmp_93093 = (NI)(TMP241);
		nimln(1598, "system.nim");
		res_93096 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP243;
				if (!(res_93096 <= HEX3Atmp_93093)) goto LA3;
				nimln(1600, "system.nim");
				i_93091 = res_93096;
				nimln(83, "strutils.nim");
				if ((NU)(i_93091) > (NU)(result->Sup.len)) raiseIndexError();
				if ((NU)(i_93091) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i_93091] = nsuToLowerChar(s->data[i_93091]);
				nimln(1619, "system.nim");
				TMP243 = addInt(res_93096, ((NI) 1));
				res_93096 = (NI)(TMP243);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len) {
	NimStringDesc* result;
	NI64 n;
	nimfr("toHex", "strutils.nim")
	result = 0;
	nimln(396, "strutils.nim");
	n = x;
	nimln(397, "strutils.nim");
	result = mnewString(((NI) (len)));
	{
		NI j_94423;
		NI HEX3Atmp_94426;
		NI TMP244;
		NI res_94429;
		j_94423 = 0;
		HEX3Atmp_94426 = 0;
		nimln(398, "strutils.nim");
		TMP244 = subInt(((NI) (len)), ((NI) 1));
		HEX3Atmp_94426 = (NI)(TMP244);
		nimln(1586, "system.nim");
		res_94429 = ((NI) (HEX3Atmp_94426));
		{
			nimln(1587, "system.nim");
			while (1) {
				NI TMP246;
				if (!(((NI) 0) <= res_94429)) goto LA3;
				nimln(1588, "system.nim");
				j_94423 = ((NI)chckRange(res_94429, ((NI) 0), ((NI) IL64(9223372036854775806))));
				nimln(399, "strutils.nim");
				if ((NU)(j_94423) > (NU)(result->Sup.len)) raiseIndexError();
				if ((NU)((NI64)(n & IL64(15))) > (NU)(((NimStringDesc*) &TMP245)->Sup.len)) raiseIndexError();
				result->data[j_94423] = ((NimStringDesc*) &TMP245)->data[(NI64)(n & IL64(15))];
				nimln(400, "strutils.nim");
				n = (NI64)((NU64)(n) >> (NU64)(IL64(4)));
				nimln(402, "strutils.nim");
				{
					NIM_BOOL LOC6;
					LOC6 = 0;
					LOC6 = (n == IL64(0));
					if (!(LOC6)) goto LA7;
					LOC6 = (x < IL64(0));
					LA7: ;
					if (!LOC6) goto LA8;
					n = IL64(-1);
				}
				LA8: ;
				nimln(1589, "system.nim");
				TMP246 = subInt(res_94429, ((NI) 1));
				res_94429 = (NI)(TMP246);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void) {
}

