/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Users\apens_000\Downloads\nim-original\lib -o c:\users\apens_000\documents\nimcode\nimdigest\tiger\nimcache\tiger.o c:\users\apens_000\documents\nimcode\nimdigest\tiger\nimcache\tiger.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct Tigerdigest102008 Tigerdigest102008;
typedef struct TY102013 TY102013;
typedef struct TY102016 TY102016;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY103106 TY103106;
typedef struct TY103428 TY103428;
typedef struct NimStringDesc NimStringDesc;
typedef struct Slice85461 Slice85461;
typedef struct TY103661 TY103661;
struct  Tigerdigest102008  {
NU64 a;
NU64 b;
NU64 c;
NI bytecount;
TY102013* buf;
NI boff;
TY102016* x;
NI xoff;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU64 TY89006[256];
struct TY103106 {
NU64 Field0;
NU64 Field1;
NU64 Field2;
};
struct TY103428 {
NI Field0;
NI Field1;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Slice85461  {
NI a;
NI b;
};
struct TY103661 {
TY102013* Field0;
TY102013* Field1;
TY102013* Field2;
};
struct TY102013 {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
struct TY102016 {
  TGenericSeq Sup;
  NU64 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, reset_102022)(Tigerdigest102008* t);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(TY102013*, newseq_102108)(NI len);
N_NIMCALL(void, TMP151)(void* p, NI op);
N_NIMCALL(TY102016*, newseq_102148)(NI len);
N_NIMCALL(void, TMP152)(void* p, NI op);
N_NIMCALL(void, inittigerdigest_102103)(Tigerdigest102008* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(void, HEX2AHEX3D_102370)(NU64* x, NU64 y);
N_NIMCALL(void, roundabc_102193)(Tigerdigest102008* t, NU64 x, NU64 mul);
N_NIMCALL(void, roundbca_102415)(Tigerdigest102008* t, NU64 x, NU64 mul);
N_NIMCALL(void, roundcab_102621)(Tigerdigest102008* t, NU64 x, NU64 mul);
N_NIMCALL(void, keyschedule_102827)(Tigerdigest102008* t);
N_NIMCALL(void, processblock_103102)(Tigerdigest102008* t);
N_NIMCALL(void, processword_103179)(Tigerdigest102008* t, TY102013* b, NI off);
N_NIMCALL(void, unpackword_103357)(NI r, TY102013** outbytes, NI outoff);
N_NIMCALL(void, processlength_103370)(Tigerdigest102008* t, NI bitlength);
N_NIMCALL(void, update_103382)(Tigerdigest102008* t, NU8 inbyte);
N_NIMCALL(void, update_103419)(Tigerdigest102008* t, TY102013** inbytes, NI inoff, NI length);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, finish_103521)(Tigerdigest102008* t);
N_NIMCALL(NI, dofinal_103539)(Tigerdigest102008* t, TY102013** outbytes, NI outoff);
N_NIMCALL(TY102013*, getbytes_103557)(NimStringDesc* s);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_81004, TNimType* mt);
N_NIMCALL(TY102013*, HEX5BHEX5D_103676)(TY102013* s, Slice85461 x);
N_NIMCALL(TY102013*, HEX26_103786)(TY102013* x, TY102013* y);
N_NIMCALL(TY102013*, tigerbytes_103615)(NimStringDesc* s);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(Slice85461, HEX2EHEX2E_103663)(NI a, NI b);
N_NIMCALL(TY102013*, tigerbytes_103924)(TY102013* s);
N_NIMCALL(NimStringDesc*, tiger_104071)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, failedassertimpl_86189)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, tiger_104235)(TY102013* s);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_sboxesInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_sboxesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_compressInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_compressDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, tigerInit)(void);
NIM_EXTERNC N_NOINLINE(void, tigerDatInit)(void);
extern NIM_CONST TY89006 Table1_89005;
extern NIM_CONST TY89006 Table2_89011;
extern NIM_CONST TY89006 Table3_89017;
extern NIM_CONST TY89006 Table4_89023;
STRING_LITERAL(TMP193, "", 0);
STRING_LITERAL(TMP201, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TMP203, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+"
"-ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+"
"-", 128);
STRING_LITERAL(TMP204, "00b83eb4e53440c576ac6aaee0a7485825fd15e70a59ffe4", 48);
STRING_LITERAL(TMP205, "tiger(\"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123"
"456789+-ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123"
"456789+-\") ==\015\012    \"00b83eb4e53440c576ac6aaee0a7485825fd15e70a59"
"ffe4\" ", 197);
STRING_LITERAL(TMP206, "24f0130c63ac933216166e76b1bb925ff373de2d49584e7a", 48);
STRING_LITERAL(TMP207, "tiger(\"\") == \"24f0130c63ac933216166e76b1bb925ff373de2d49584e7a\""
" ", 64);
extern TFrame* frameptr_17042;
extern TNimType NTI3405; /* byte */
TNimType NTI102013; /* seq[byte] */
extern TNimType NTI126; /* uint64 */
TNimType NTI102016; /* seq[uint64] */

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(void, reset_102022)(Tigerdigest102008* t) {
	nimfr("reset", "tiger.nim")
	nimln(20, "tiger.nim");
	(*t).a = 81985529216486895ULL;
	nimln(21, "tiger.nim");
	(*t).b = 18364758544493064720ULL;
	nimln(22, "tiger.nim");
	(*t).c = 17336226011405279623ULL;
	nimln(23, "tiger.nim");
	(*t).xoff = ((NI) 0);
	{
		NI i_102044;
		NI res_102068;
		i_102044 = 0;
		nimln(1598, "system.nim");
		res_102068 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP149;
				if (!(res_102068 <= ((NI) 7))) goto LA3;
				nimln(1600, "system.nim");
				i_102044 = res_102068;
				nimln(25, "tiger.nim");
				if ((NU)(i_102044) >= (NU)((*t).x->Sup.len)) raiseIndexError();
				(*t).x->data[i_102044] = 0ULL;
				nimln(1619, "system.nim");
				TMP149 = addInt(res_102068, ((NI) 1));
				res_102068 = (NI)(TMP149);
			} LA3: ;
		}
	}
	nimln(26, "tiger.nim");
	(*t).boff = ((NI) 0);
	{
		NI i_102063;
		NI res_102075;
		i_102063 = 0;
		nimln(1598, "system.nim");
		res_102075 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP150;
				if (!(res_102075 <= ((NI) 7))) goto LA6;
				nimln(1600, "system.nim");
				i_102063 = res_102075;
				nimln(28, "tiger.nim");
				if ((NU)(i_102063) >= (NU)((*t).buf->Sup.len)) raiseIndexError();
				(*t).buf->data[i_102063] = ((NU8) 0);
				nimln(1619, "system.nim");
				TMP150 = addInt(res_102075, ((NI) 1));
				res_102075 = (NI)(TMP150);
			} LA6: ;
		}
	}
	nimln(29, "tiger.nim");
	(*t).bytecount = ((NI) 0);
	popFrame();
}
N_NIMCALL(void, TMP151)(void* p, NI op) {
	TY102013* a;
	NI LOC1;
	a = (TY102013*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}
N_NIMCALL(void, TMP152)(void* p, NI op) {
	TY102016* a;
	NI LOC1;
	a = (TY102016*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(void, inittigerdigest_102103)(Tigerdigest102008* Result) {
	nimfr("initTigerDigest", "tiger.nim")
	nimln(32, "tiger.nim");
	unsureAsgnRef((void**) (&(*Result).buf), newseq_102108(((NI) 8)));
	nimln(33, "tiger.nim");
	unsureAsgnRef((void**) (&(*Result).x), newseq_102148(((NI) 8)));
	nimln(34, "tiger.nim");
	(*Result).boff = ((NI) 0);
	nimln(35, "tiger.nim");
	(*Result).xoff = ((NI) 0);
	nimln(36, "tiger.nim");
	reset_102022(Result);
	popFrame();
}

static N_INLINE(void, HEX2AHEX3D_102370)(NU64* x, NU64 y) {
	nimfr("*=", "system.nim")
	nimln(2989, "system.nim");
	(*x) = (NU64)((NU64)((*x)) * (NU64)(y));
	popFrame();
}

N_NIMCALL(void, roundabc_102193)(Tigerdigest102008* t, NU64 x, NU64 mul) {
	nimfr("roundABC", "tiger.nim")
	nimln(39, "tiger.nim");
	(*t).c = (NU64)((*t).c ^ x);
	nimln(40, "tiger.nim");
	nimln(41, "tiger.nim");
	nimln(40, "tiger.nim");
	nimln(41, "tiger.nim");
	(*t).a -= (NU64)((NU64)((NU64)(Table1_89005[((NI)(((NI) ((*t).c)) & ((NI) 255)))- 0] ^ Table2_89011[((NI)(((NI) ((NU64)((NU64)((*t).c) >> (NU64)(16ULL)))) & ((NI) 255)))- 0]) ^ Table3_89017[((NI)(((NI) ((NU64)((NU64)((*t).c) >> (NU64)(32ULL)))) & ((NI) 255)))- 0]) ^ Table4_89023[((NI)(((NI) ((NU64)((NU64)((*t).c) >> (NU64)(48ULL)))) & ((NI) 255)))- 0]);
	nimln(42, "tiger.nim");
	nimln(43, "tiger.nim");
	nimln(42, "tiger.nim");
	nimln(43, "tiger.nim");
	(*t).b += (NU64)((NU64)((NU64)(Table4_89023[((NI)(((NI) ((NU64)((NU64)((*t).c) >> (NU64)(8ULL)))) & ((NI) 255)))- 0] ^ Table3_89017[((NI)(((NI) ((NU64)((NU64)((*t).c) >> (NU64)(24ULL)))) & ((NI) 255)))- 0]) ^ Table2_89011[((NI)(((NI) ((NU64)((NU64)((*t).c) >> (NU64)(40ULL)))) & ((NI) 255)))- 0]) ^ Table1_89005[((NI)(((NI) ((NU64)((NU64)((*t).c) >> (NU64)(56ULL)))) & ((NI) 255)))- 0]);
	nimln(44, "tiger.nim");
	HEX2AHEX3D_102370((&(*t).b), mul);
	popFrame();
}

N_NIMCALL(void, roundbca_102415)(Tigerdigest102008* t, NU64 x, NU64 mul) {
	nimfr("roundBCA", "tiger.nim")
	nimln(47, "tiger.nim");
	(*t).a = (NU64)((*t).a ^ x);
	nimln(48, "tiger.nim");
	nimln(49, "tiger.nim");
	nimln(48, "tiger.nim");
	nimln(49, "tiger.nim");
	(*t).b -= (NU64)((NU64)((NU64)(Table1_89005[((NI)(((NI) ((*t).a)) & ((NI) 255)))- 0] ^ Table2_89011[((NI)(((NI) ((NU64)((NU64)((*t).a) >> (NU64)(16ULL)))) & ((NI) 255)))- 0]) ^ Table3_89017[((NI)(((NI) ((NU64)((NU64)((*t).a) >> (NU64)(32ULL)))) & ((NI) 255)))- 0]) ^ Table4_89023[((NI)(((NI) ((NU64)((NU64)((*t).a) >> (NU64)(48ULL)))) & ((NI) 255)))- 0]);
	nimln(50, "tiger.nim");
	nimln(51, "tiger.nim");
	nimln(50, "tiger.nim");
	nimln(51, "tiger.nim");
	(*t).c += (NU64)((NU64)((NU64)(Table4_89023[((NI)(((NI) ((NU64)((NU64)((*t).a) >> (NU64)(8ULL)))) & ((NI) 255)))- 0] ^ Table3_89017[((NI)(((NI) ((NU64)((NU64)((*t).a) >> (NU64)(24ULL)))) & ((NI) 255)))- 0]) ^ Table2_89011[((NI)(((NI) ((NU64)((NU64)((*t).a) >> (NU64)(40ULL)))) & ((NI) 255)))- 0]) ^ Table1_89005[((NI)(((NI) ((NU64)((NU64)((*t).a) >> (NU64)(56ULL)))) & ((NI) 255)))- 0]);
	nimln(52, "tiger.nim");
	HEX2AHEX3D_102370((&(*t).c), mul);
	popFrame();
}

N_NIMCALL(void, roundcab_102621)(Tigerdigest102008* t, NU64 x, NU64 mul) {
	nimfr("roundCAB", "tiger.nim")
	nimln(55, "tiger.nim");
	(*t).b = (NU64)((*t).b ^ x);
	nimln(56, "tiger.nim");
	nimln(57, "tiger.nim");
	nimln(56, "tiger.nim");
	nimln(57, "tiger.nim");
	(*t).c -= (NU64)((NU64)((NU64)(Table1_89005[((NI)(((NI) ((*t).b)) & ((NI) 255)))- 0] ^ Table2_89011[((NI)(((NI) ((NU64)((NU64)((*t).b) >> (NU64)(16ULL)))) & ((NI) 255)))- 0]) ^ Table3_89017[((NI)(((NI) ((NU64)((NU64)((*t).b) >> (NU64)(32ULL)))) & ((NI) 255)))- 0]) ^ Table4_89023[((NI)(((NI) ((NU64)((NU64)((*t).b) >> (NU64)(48ULL)))) & ((NI) 255)))- 0]);
	nimln(58, "tiger.nim");
	nimln(59, "tiger.nim");
	nimln(58, "tiger.nim");
	nimln(59, "tiger.nim");
	(*t).a += (NU64)((NU64)((NU64)(Table4_89023[((NI)(((NI) ((NU64)((NU64)((*t).b) >> (NU64)(8ULL)))) & ((NI) 255)))- 0] ^ Table3_89017[((NI)(((NI) ((NU64)((NU64)((*t).b) >> (NU64)(24ULL)))) & ((NI) 255)))- 0]) ^ Table2_89011[((NI)(((NI) ((NU64)((NU64)((*t).b) >> (NU64)(40ULL)))) & ((NI) 255)))- 0]) ^ Table1_89005[((NI)(((NI) ((NU64)((NU64)((*t).b) >> (NU64)(56ULL)))) & ((NI) 255)))- 0]);
	nimln(60, "tiger.nim");
	HEX2AHEX3D_102370((&(*t).a), mul);
	popFrame();
}

N_NIMCALL(void, keyschedule_102827)(Tigerdigest102008* t) {
	nimfr("keySchedule", "tiger.nim")
	nimln(63, "tiger.nim");
	if ((NU)(((NI) 0)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 7)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 0)] -= (NU64)((*t).x->data[((NI) 7)] ^ 11936128518282651045ULL);
	nimln(64, "tiger.nim");
	if ((NU)(((NI) 1)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 1)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 0)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 1)] = (NU64)((*t).x->data[((NI) 1)] ^ (*t).x->data[((NI) 0)]);
	nimln(65, "tiger.nim");
	if ((NU)(((NI) 2)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 1)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 2)] += (*t).x->data[((NI) 1)];
	nimln(66, "tiger.nim");
	if ((NU)(((NI) 3)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 2)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 1)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 3)] -= (NU64)((*t).x->data[((NI) 2)] ^ (NU64)((NU64)((NU64)((NU64) ~((*t).x->data[((NI) 1)]))) << (NU64)(((NI) 19))));
	nimln(67, "tiger.nim");
	if ((NU)(((NI) 4)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 4)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 3)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 4)] = (NU64)((*t).x->data[((NI) 4)] ^ (*t).x->data[((NI) 3)]);
	nimln(68, "tiger.nim");
	if ((NU)(((NI) 5)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 4)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 5)] += (*t).x->data[((NI) 4)];
	nimln(69, "tiger.nim");
	if ((NU)(((NI) 6)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 5)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 4)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 6)] -= (NU64)((*t).x->data[((NI) 5)] ^ (NU64)((NU64)((NU64)((NU64) ~((*t).x->data[((NI) 4)]))) >> (NU64)(((NI) 23))));
	nimln(70, "tiger.nim");
	if ((NU)(((NI) 7)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 7)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 6)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 7)] = (NU64)((*t).x->data[((NI) 7)] ^ (*t).x->data[((NI) 6)]);
	nimln(71, "tiger.nim");
	if ((NU)(((NI) 0)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 7)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 0)] += (*t).x->data[((NI) 7)];
	nimln(72, "tiger.nim");
	if ((NU)(((NI) 1)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 0)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 7)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 1)] -= (NU64)((*t).x->data[((NI) 0)] ^ (NU64)((NU64)((NU64)((NU64) ~((*t).x->data[((NI) 7)]))) << (NU64)(((NI) 19))));
	nimln(73, "tiger.nim");
	if ((NU)(((NI) 2)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 2)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 1)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 2)] = (NU64)((*t).x->data[((NI) 2)] ^ (*t).x->data[((NI) 1)]);
	nimln(74, "tiger.nim");
	if ((NU)(((NI) 3)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 2)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 3)] += (*t).x->data[((NI) 2)];
	nimln(75, "tiger.nim");
	if ((NU)(((NI) 4)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 3)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 2)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 4)] -= (NU64)((*t).x->data[((NI) 3)] ^ (NU64)((NU64)((NU64)((NU64) ~((*t).x->data[((NI) 2)]))) >> (NU64)(((NI) 23))));
	nimln(76, "tiger.nim");
	if ((NU)(((NI) 5)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 5)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 4)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 5)] = (NU64)((*t).x->data[((NI) 5)] ^ (*t).x->data[((NI) 4)]);
	nimln(77, "tiger.nim");
	if ((NU)(((NI) 6)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 5)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 6)] += (*t).x->data[((NI) 5)];
	nimln(78, "tiger.nim");
	if ((NU)(((NI) 7)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 6)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 7)] -= (NU64)((*t).x->data[((NI) 6)] ^ ((NI) IL64(81985529216486895)));
	popFrame();
}

N_NIMCALL(void, processblock_103102)(Tigerdigest102008* t) {
	TY103106 LOC1;
	NU64 aa;
	NU64 bb;
	NU64 cc;
	nimfr("processBlock", "tiger.nim")
	nimln(82, "tiger.nim");
	LOC1.Field0 = (*t).a;
	LOC1.Field1 = (*t).b;
	LOC1.Field2 = (*t).c;
	aa = LOC1.Field0;
	bb = LOC1.Field1;
	cc = LOC1.Field2;
	nimln(85, "tiger.nim");
	if ((NU)(((NI) 0)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundabc_102193(t, (*t).x->data[((NI) 0)], 5ULL);
	nimln(86, "tiger.nim");
	if ((NU)(((NI) 1)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundbca_102415(t, (*t).x->data[((NI) 1)], 5ULL);
	nimln(87, "tiger.nim");
	if ((NU)(((NI) 2)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundcab_102621(t, (*t).x->data[((NI) 2)], 5ULL);
	nimln(88, "tiger.nim");
	if ((NU)(((NI) 3)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundabc_102193(t, (*t).x->data[((NI) 3)], 5ULL);
	nimln(89, "tiger.nim");
	if ((NU)(((NI) 4)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundbca_102415(t, (*t).x->data[((NI) 4)], 5ULL);
	nimln(90, "tiger.nim");
	if ((NU)(((NI) 5)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundcab_102621(t, (*t).x->data[((NI) 5)], 5ULL);
	nimln(91, "tiger.nim");
	if ((NU)(((NI) 6)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundabc_102193(t, (*t).x->data[((NI) 6)], 5ULL);
	nimln(92, "tiger.nim");
	if ((NU)(((NI) 7)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundbca_102415(t, (*t).x->data[((NI) 7)], 5ULL);
	nimln(94, "tiger.nim");
	keyschedule_102827(t);
	nimln(96, "tiger.nim");
	if ((NU)(((NI) 0)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundcab_102621(t, (*t).x->data[((NI) 0)], 7ULL);
	nimln(97, "tiger.nim");
	if ((NU)(((NI) 1)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundabc_102193(t, (*t).x->data[((NI) 1)], 7ULL);
	nimln(98, "tiger.nim");
	if ((NU)(((NI) 2)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundbca_102415(t, (*t).x->data[((NI) 2)], 7ULL);
	nimln(99, "tiger.nim");
	if ((NU)(((NI) 3)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundcab_102621(t, (*t).x->data[((NI) 3)], 7ULL);
	nimln(100, "tiger.nim");
	if ((NU)(((NI) 4)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundabc_102193(t, (*t).x->data[((NI) 4)], 7ULL);
	nimln(101, "tiger.nim");
	if ((NU)(((NI) 5)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundbca_102415(t, (*t).x->data[((NI) 5)], 7ULL);
	nimln(102, "tiger.nim");
	if ((NU)(((NI) 6)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundcab_102621(t, (*t).x->data[((NI) 6)], 7ULL);
	nimln(103, "tiger.nim");
	if ((NU)(((NI) 7)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundabc_102193(t, (*t).x->data[((NI) 7)], 7ULL);
	nimln(105, "tiger.nim");
	keyschedule_102827(t);
	nimln(107, "tiger.nim");
	if ((NU)(((NI) 0)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundbca_102415(t, (*t).x->data[((NI) 0)], 9ULL);
	nimln(108, "tiger.nim");
	if ((NU)(((NI) 1)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundcab_102621(t, (*t).x->data[((NI) 1)], 9ULL);
	nimln(109, "tiger.nim");
	if ((NU)(((NI) 2)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundabc_102193(t, (*t).x->data[((NI) 2)], 9ULL);
	nimln(110, "tiger.nim");
	if ((NU)(((NI) 3)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundbca_102415(t, (*t).x->data[((NI) 3)], 9ULL);
	nimln(111, "tiger.nim");
	if ((NU)(((NI) 4)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundcab_102621(t, (*t).x->data[((NI) 4)], 9ULL);
	nimln(112, "tiger.nim");
	if ((NU)(((NI) 5)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundabc_102193(t, (*t).x->data[((NI) 5)], 9ULL);
	nimln(113, "tiger.nim");
	if ((NU)(((NI) 6)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundbca_102415(t, (*t).x->data[((NI) 6)], 9ULL);
	nimln(114, "tiger.nim");
	if ((NU)(((NI) 7)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	roundcab_102621(t, (*t).x->data[((NI) 7)], 9ULL);
	nimln(117, "tiger.nim");
	(*t).a = (NU64)((*t).a ^ aa);
	nimln(118, "tiger.nim");
	(*t).b -= bb;
	nimln(119, "tiger.nim");
	(*t).c += cc;
	nimln(122, "tiger.nim");
	(*t).xoff = ((NI) 0);
	{
		NI i_103155;
		NI res_103160;
		i_103155 = 0;
		nimln(1598, "system.nim");
		res_103160 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP153;
				if (!(res_103160 <= ((NI) 7))) goto LA4;
				nimln(1600, "system.nim");
				i_103155 = res_103160;
				nimln(124, "tiger.nim");
				if ((NU)(i_103155) >= (NU)((*t).x->Sup.len)) raiseIndexError();
				(*t).x->data[i_103155] = 0ULL;
				nimln(1619, "system.nim");
				TMP153 = addInt(res_103160, ((NI) 1));
				res_103160 = (NI)(TMP153);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, processword_103179)(Tigerdigest102008* t, TY102013* b, NI off) {
	NI TMP154;
	NI TMP155;
	NI TMP156;
	NI TMP157;
	NI TMP158;
	NI TMP159;
	NI TMP160;
	NI TMP161;
	NI TMP162;
	nimfr("processWord", "tiger.nim")
	nimln(129, "tiger.nim");
	if ((NU)((*t).xoff) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	nimln(135, "tiger.nim");
	nimln(134, "tiger.nim");
	nimln(133, "tiger.nim");
	nimln(132, "tiger.nim");
	nimln(131, "tiger.nim");
	nimln(130, "tiger.nim");
	nimln(129, "tiger.nim");
	TMP154 = addInt(off, ((NI) 7));
	if ((NU)((NI)(TMP154)) >= (NU)(b->Sup.len)) raiseIndexError();
	nimln(130, "tiger.nim");
	TMP155 = addInt(off, ((NI) 6));
	if ((NU)((NI)(TMP155)) >= (NU)(b->Sup.len)) raiseIndexError();
	nimln(131, "tiger.nim");
	TMP156 = addInt(off, ((NI) 5));
	if ((NU)((NI)(TMP156)) >= (NU)(b->Sup.len)) raiseIndexError();
	nimln(132, "tiger.nim");
	TMP157 = addInt(off, ((NI) 4));
	if ((NU)((NI)(TMP157)) >= (NU)(b->Sup.len)) raiseIndexError();
	nimln(133, "tiger.nim");
	TMP158 = addInt(off, ((NI) 3));
	if ((NU)((NI)(TMP158)) >= (NU)(b->Sup.len)) raiseIndexError();
	nimln(134, "tiger.nim");
	TMP159 = addInt(off, ((NI) 2));
	if ((NU)((NI)(TMP159)) >= (NU)(b->Sup.len)) raiseIndexError();
	nimln(135, "tiger.nim");
	TMP160 = addInt(off, ((NI) 1));
	if ((NU)((NI)(TMP160)) >= (NU)(b->Sup.len)) raiseIndexError();
	nimln(136, "tiger.nim");
	TMP161 = addInt(off, ((NI) 0));
	if ((NU)((NI)(TMP161)) >= (NU)(b->Sup.len)) raiseIndexError();
	(*t).x->data[(*t).xoff] = (NU64)((NU64)((NU64)((NU64)((NU64)((NU64)((NU64)(((NU64) ((NI)((NU64)(((NI) ((NU8)(b->data[(NI)(TMP154)] & ((NI) 255))))) << (NU64)(((NI) 56))))) | ((NU64) ((NI)((NU64)(((NI) ((NU8)(b->data[(NI)(TMP155)] & ((NI) 255))))) << (NU64)(((NI) 48)))))) | ((NU64) ((NI)((NU64)(((NI) ((NU8)(b->data[(NI)(TMP156)] & ((NI) 255))))) << (NU64)(((NI) 40)))))) | ((NU64) ((NI)((NU64)(((NI) ((NU8)(b->data[(NI)(TMP157)] & ((NI) 255))))) << (NU64)(((NI) 32)))))) | ((NU64) ((NI)((NU64)(((NI) ((NU8)(b->data[(NI)(TMP158)] & ((NI) 255))))) << (NU64)(((NI) 24)))))) | ((NU64) ((NI)((NU64)(((NI) ((NU8)(b->data[(NI)(TMP159)] & ((NI) 255))))) << (NU64)(((NI) 16)))))) | ((NU64) ((NI)((NU64)(((NI) ((NU8)(b->data[(NI)(TMP160)] & ((NI) 255))))) << (NU64)(((NI) 8)))))) | ((NU64) (b->data[(NI)(TMP161)])));
	nimln(137, "tiger.nim");
	TMP162 = addInt((*t).xoff, ((NI) 1));
	(*t).xoff = (NI)(TMP162);
	nimln(139, "tiger.nim");
	{
		if (!((*t).xoff == ((*t).x ? (*t).x->Sup.len : 0))) goto LA3;
		nimln(140, "tiger.nim");
		processblock_103102(t);
	}
	LA3: ;
	nimln(142, "tiger.nim");
	(*t).boff = ((NI) 0);
	popFrame();
}

N_NIMCALL(void, unpackword_103357)(NI r, TY102013** outbytes, NI outoff) {
	NI TMP163;
	NI TMP164;
	NI TMP165;
	NI TMP166;
	NI TMP167;
	NI TMP168;
	NI TMP169;
	NI TMP170;
	nimfr("unpackWord", "tiger.nim")
	nimln(145, "tiger.nim");
	TMP163 = addInt(outoff, ((NI) 7));
	if ((NU)((NI)(TMP163)) >= (NU)((*outbytes)->Sup.len)) raiseIndexError();
	(*outbytes)->data[(NI)(TMP163)] = ((NU8) ((NI)((NU64)(r) >> (NU64)(((NI) 56)))));
	nimln(146, "tiger.nim");
	TMP164 = addInt(outoff, ((NI) 6));
	if ((NU)((NI)(TMP164)) >= (NU)((*outbytes)->Sup.len)) raiseIndexError();
	(*outbytes)->data[(NI)(TMP164)] = ((NU8) ((NI)((NU64)(r) >> (NU64)(((NI) 48)))));
	nimln(147, "tiger.nim");
	TMP165 = addInt(outoff, ((NI) 5));
	if ((NU)((NI)(TMP165)) >= (NU)((*outbytes)->Sup.len)) raiseIndexError();
	(*outbytes)->data[(NI)(TMP165)] = ((NU8) ((NI)((NU64)(r) >> (NU64)(((NI) 40)))));
	nimln(148, "tiger.nim");
	TMP166 = addInt(outoff, ((NI) 4));
	if ((NU)((NI)(TMP166)) >= (NU)((*outbytes)->Sup.len)) raiseIndexError();
	(*outbytes)->data[(NI)(TMP166)] = ((NU8) ((NI)((NU64)(r) >> (NU64)(((NI) 32)))));
	nimln(149, "tiger.nim");
	TMP167 = addInt(outoff, ((NI) 3));
	if ((NU)((NI)(TMP167)) >= (NU)((*outbytes)->Sup.len)) raiseIndexError();
	(*outbytes)->data[(NI)(TMP167)] = ((NU8) ((NI)((NU64)(r) >> (NU64)(((NI) 24)))));
	nimln(150, "tiger.nim");
	TMP168 = addInt(outoff, ((NI) 2));
	if ((NU)((NI)(TMP168)) >= (NU)((*outbytes)->Sup.len)) raiseIndexError();
	(*outbytes)->data[(NI)(TMP168)] = ((NU8) ((NI)((NU64)(r) >> (NU64)(((NI) 16)))));
	nimln(151, "tiger.nim");
	TMP169 = addInt(outoff, ((NI) 1));
	if ((NU)((NI)(TMP169)) >= (NU)((*outbytes)->Sup.len)) raiseIndexError();
	(*outbytes)->data[(NI)(TMP169)] = ((NU8) ((NI)((NU64)(r) >> (NU64)(((NI) 8)))));
	nimln(152, "tiger.nim");
	TMP170 = addInt(outoff, ((NI) 0));
	if ((NU)((NI)(TMP170)) >= (NU)((*outbytes)->Sup.len)) raiseIndexError();
	(*outbytes)->data[(NI)(TMP170)] = ((NU8) (r));
	popFrame();
}

N_NIMCALL(void, processlength_103370)(Tigerdigest102008* t, NI bitlength) {
	nimfr("processLength", "tiger.nim")
	nimln(155, "tiger.nim");
	if ((NU)(((NI) 7)) >= (NU)((*t).x->Sup.len)) raiseIndexError();
	(*t).x->data[((NI) 7)] = ((NU64) (bitlength));
	popFrame();
}

N_NIMCALL(void, update_103382)(Tigerdigest102008* t, NU8 inbyte) {
	NI TMP171;
	NI TMP172;
	nimfr("update", "tiger.nim")
	nimln(158, "tiger.nim");
	if ((NU)((*t).boff) >= (NU)((*t).buf->Sup.len)) raiseIndexError();
	(*t).buf->data[(*t).boff] = inbyte;
	nimln(159, "tiger.nim");
	TMP171 = addInt((*t).boff, ((NI) 1));
	(*t).boff = (NI)(TMP171);
	nimln(161, "tiger.nim");
	{
		if (!((*t).boff == ((*t).buf ? (*t).buf->Sup.len : 0))) goto LA3;
		nimln(162, "tiger.nim");
		processword_103179(t, (*t).buf, ((NI) 0));
	}
	LA3: ;
	nimln(164, "tiger.nim");
	TMP172 = addInt((*t).bytecount, ((NI) 1));
	(*t).bytecount = (NI)(TMP172);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, update_103419)(Tigerdigest102008* t, TY102013** inbytes, NI inoff, NI length) {
	TY103428 LOC1;
	NI myinoff;
	NI mylen;
	nimfr("update", "tiger.nim")
	nimln(168, "tiger.nim");
	LOC1.Field0 = inoff;
	LOC1.Field1 = length;
	myinoff = LOC1.Field0;
	mylen = LOC1.Field1;
	{
		nimln(169, "tiger.nim");
		while (1) {
			NIM_BOOL LOC4;
			NI TMP173;
			NI TMP174;
			LOC4 = 0;
			LOC4 = !(((*t).boff == ((NI) 0)));
			if (!(LOC4)) goto LA5;
			LOC4 = (((NI) 0) < mylen);
			LA5: ;
			if (!LOC4) goto LA3;
			nimln(170, "tiger.nim");
			if ((NU)(myinoff) >= (NU)((*inbytes)->Sup.len)) raiseIndexError();
			update_103382(t, (*inbytes)->data[myinoff]);
			nimln(171, "tiger.nim");
			TMP173 = addInt(myinoff, ((NI) 1));
			myinoff = (NI)(TMP173);
			nimln(172, "tiger.nim");
			TMP174 = subInt(mylen, ((NI) 1));
			mylen = (NI)(TMP174);
		} LA3: ;
	}
	{
		nimln(175, "tiger.nim");
		while (1) {
			NI TMP175;
			NI TMP176;
			NI TMP177;
			if (!(((NI) 8) < mylen)) goto LA7;
			nimln(176, "tiger.nim");
			processword_103179(t, (*inbytes), myinoff);
			nimln(178, "tiger.nim");
			TMP175 = addInt(myinoff, ((NI) 8));
			myinoff = (NI)(TMP175);
			nimln(179, "tiger.nim");
			TMP176 = subInt(mylen, ((NI) 8));
			mylen = (NI)(TMP176);
			nimln(180, "tiger.nim");
			TMP177 = addInt((*t).bytecount, ((NI) 8));
			(*t).bytecount = (NI)(TMP177);
		} LA7: ;
	}
	{
		nimln(183, "tiger.nim");
		while (1) {
			NI TMP178;
			NI TMP179;
			if (!(((NI) 0) < mylen)) goto LA9;
			nimln(184, "tiger.nim");
			if ((NU)(myinoff) >= (NU)((*inbytes)->Sup.len)) raiseIndexError();
			update_103382(t, (*inbytes)->data[myinoff]);
			nimln(185, "tiger.nim");
			TMP178 = addInt(myinoff, ((NI) 1));
			myinoff = (NI)(TMP178);
			nimln(186, "tiger.nim");
			TMP179 = subInt(mylen, ((NI) 1));
			mylen = (NI)(TMP179);
		} LA9: ;
	}
	popFrame();
}

N_NIMCALL(void, finish_103521)(Tigerdigest102008* t) {
	NI bitlength;
	nimfr("finish", "tiger.nim")
	nimln(189, "tiger.nim");
	bitlength = (NI)((NU64)((*t).bytecount) << (NU64)(((NI) 3)));
	nimln(191, "tiger.nim");
	update_103382(t, ((NU8) 1));
	{
		nimln(193, "tiger.nim");
		while (1) {
			if (!!(((*t).boff == ((NI) 0)))) goto LA2;
			nimln(194, "tiger.nim");
			update_103382(t, ((NU8) 0));
		} LA2: ;
	}
	nimln(196, "tiger.nim");
	processlength_103370(t, bitlength);
	nimln(198, "tiger.nim");
	processblock_103102(t);
	popFrame();
}

N_NIMCALL(NI, dofinal_103539)(Tigerdigest102008* t, TY102013** outbytes, NI outoff) {
	NI result;
	NI TMP180;
	NI TMP181;
	nimfr("doFinal", "tiger.nim")
	result = 0;
	nimln(201, "tiger.nim");
	finish_103521(t);
	nimln(203, "tiger.nim");
	unpackword_103357(((NI) ((*t).a)), outbytes, outoff);
	nimln(204, "tiger.nim");
	TMP180 = addInt(outoff, ((NI) 8));
	unpackword_103357(((NI) ((*t).b)), outbytes, (NI)(TMP180));
	nimln(205, "tiger.nim");
	TMP181 = addInt(outoff, ((NI) 16));
	unpackword_103357(((NI) ((*t).c)), outbytes, (NI)(TMP181));
	nimln(207, "tiger.nim");
	reset_102022(t);
	nimln(209, "tiger.nim");
	result = ((NI) 24);
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(TY102013*, getbytes_103557)(NimStringDesc* s) {
	TY102013* result;
	NI i;
	TY102013* abyte0;
	NI j;
	nimfr("getBytes", "tiger.nim")
	result = 0;
	nimln(213, "tiger.nim");
	i = (s ? s->Sup.len : 0);
	nimln(214, "tiger.nim");
	abyte0 = newseq_102108(((NI)chckRange(i, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(215, "tiger.nim");
	j = ((NI) 0);
	{
		nimln(217, "tiger.nim");
		while (1) {
			NI TMP182;
			if (!(j < i)) goto LA2;
			nimln(218, "tiger.nim");
			if ((NU)(j) >= (NU)(abyte0->Sup.len)) raiseIndexError();
			if ((NU)(j) > (NU)(s->Sup.len)) raiseIndexError();
			abyte0->data[j] = ((NU8) (((NU8)(s->data[j]))));
			nimln(219, "tiger.nim");
			TMP182 = addInt(j, ((NI) 1));
			j = (NI)(TMP182);
		} LA2: ;
	}
	nimln(221, "tiger.nim");
	genericSeqAssign((&result), abyte0, (&NTI102013));
	popFrame();
	return result;
}

static N_INLINE(Slice85461, HEX2EHEX2E_103663)(NI a, NI b) {
	Slice85461 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(234, "system.nim");
	result.a = a;
	nimln(235, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_NIMCALL(TY102013*, tigerbytes_103615)(NimStringDesc* s) {
	TY102013* result;
	Tigerdigest102008 m;
	TY102013* message;
	NI LOC1;
	TY103661 LOC2;
	Slice85461 LOC3;
	Slice85461 LOC4;
	Slice85461 LOC5;
	TY102013* tmp0;
	TY102013* tmp1;
	TY102013* tmp2;
	TY102013* LOC6;
	nimfr("tigerBytes", "tiger.nim")
	result = 0;
	memset((void*)(&m), 0, sizeof(m));
	nimln(224, "tiger.nim");
	chckNil((void*)(&m));
	memset((void*)(&m), 0, sizeof(m));
	inittigerdigest_102103((&m));
	nimln(225, "tiger.nim");
	message = getbytes_103557(s);
	nimln(226, "tiger.nim");
	update_103419((&m), (&message), ((NI) 0), (message ? message->Sup.len : 0));
	nimln(227, "tiger.nim");
	result = newseq_102108(((NI) 24));
	nimln(228, "tiger.nim");
	LOC1 = 0;
	LOC1 = dofinal_103539((&m), (&result), ((NI) 0));
	nimln(229, "tiger.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC3 = HEX2EHEX2E_103663(((NI) 16), ((NI) 23));
	LOC2.Field0 = HEX5BHEX5D_103676(result, LOC3);
	LOC4 = HEX2EHEX2E_103663(((NI) 8), ((NI) 15));
	LOC2.Field1 = HEX5BHEX5D_103676(result, LOC4);
	LOC5 = HEX2EHEX2E_103663(((NI) 0), ((NI) 7));
	LOC2.Field2 = HEX5BHEX5D_103676(result, LOC5);
	tmp0 = 0;
	genericSeqAssign((&tmp0), LOC2.Field0, (&NTI102013));
	tmp1 = 0;
	genericSeqAssign((&tmp1), LOC2.Field1, (&NTI102013));
	tmp2 = 0;
	genericSeqAssign((&tmp2), LOC2.Field2, (&NTI102013));
	nimln(230, "tiger.nim");
	LOC6 = 0;
	LOC6 = HEX26_103786(tmp0, tmp1);
	result = HEX26_103786(LOC6, tmp2);
	popFrame();
	return result;
}

N_NIMCALL(TY102013*, tigerbytes_103924)(TY102013* s) {
	TY102013* result;
	Tigerdigest102008 m;
	TY102013* message;
	NI LOC1;
	TY103661 LOC2;
	Slice85461 LOC3;
	Slice85461 LOC4;
	Slice85461 LOC5;
	TY102013* tmp0;
	TY102013* tmp1;
	TY102013* tmp2;
	TY102013* LOC6;
	nimfr("tigerBytes", "tiger.nim")
	result = 0;
	memset((void*)(&m), 0, sizeof(m));
	nimln(233, "tiger.nim");
	chckNil((void*)(&m));
	memset((void*)(&m), 0, sizeof(m));
	inittigerdigest_102103((&m));
	nimln(234, "tiger.nim");
	genericSeqAssign((&message), s, (&NTI102013));
	nimln(235, "tiger.nim");
	update_103419((&m), (&message), ((NI) 0), (message ? message->Sup.len : 0));
	nimln(236, "tiger.nim");
	result = newseq_102108(((NI) 24));
	nimln(237, "tiger.nim");
	LOC1 = 0;
	LOC1 = dofinal_103539((&m), (&result), ((NI) 0));
	nimln(238, "tiger.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC3 = HEX2EHEX2E_103663(((NI) 16), ((NI) 23));
	LOC2.Field0 = HEX5BHEX5D_103676(result, LOC3);
	LOC4 = HEX2EHEX2E_103663(((NI) 8), ((NI) 15));
	LOC2.Field1 = HEX5BHEX5D_103676(result, LOC4);
	LOC5 = HEX2EHEX2E_103663(((NI) 0), ((NI) 7));
	LOC2.Field2 = HEX5BHEX5D_103676(result, LOC5);
	tmp0 = 0;
	genericSeqAssign((&tmp0), LOC2.Field0, (&NTI102013));
	tmp1 = 0;
	genericSeqAssign((&tmp1), LOC2.Field1, (&NTI102013));
	tmp2 = 0;
	genericSeqAssign((&tmp2), LOC2.Field2, (&NTI102013));
	nimln(239, "tiger.nim");
	LOC6 = 0;
	LOC6 = HEX26_103786(tmp0, tmp1);
	result = HEX26_103786(LOC6, tmp2);
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, tiger_104071)(NimStringDesc* s) {
	NimStringDesc* result;
	TY102013* res;
	nimfr("tiger", "tiger.nim")
	result = 0;
	nimln(242, "tiger.nim");
	res = tigerbytes_103615(s);
	nimln(243, "tiger.nim");
	result = copyString(((NimStringDesc*) &TMP193));
	{
		NU8 i_104211;
		NI i_104217;
		NI L_104219;
		i_104211 = 0;
		nimln(3085, "system.nim");
		i_104217 = ((NI) 0);
		nimln(3086, "system.nim");
		L_104219 = (res ? res->Sup.len : 0);
		{
			nimln(3087, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				NimStringDesc* LOC5;
				NimStringDesc* LOC6;
				NI TMP200;
				if (!(i_104217 < L_104219)) goto LA3;
				nimln(3088, "system.nim");
				if ((NU)(i_104217) >= (NU)(res->Sup.len)) raiseIndexError();
				i_104211 = res->data[i_104217];
				nimln(245, "tiger.nim");
				LOC4 = 0;
				LOC5 = 0;
				LOC5 = nsuToHex(((NI64) (((NI) (i_104211)))), ((NI) 2));
				LOC6 = 0;
				LOC6 = nsuToLowerStr(LOC5);
				LOC4 = rawNewString(LOC6->Sup.len + result->Sup.len + 0);
appendString(LOC4, LOC6);
appendString(LOC4, result);
				result = LOC4;
				nimln(3089, "system.nim");
				TMP200 = addInt(i_104217, ((NI) 1));
				i_104217 = (NI)(TMP200);
				nimln(3090, "system.nim");
				{
					if (!!(((res ? res->Sup.len : 0) == L_104219))) goto LA9;
					failedassertimpl_86189(((NimStringDesc*) &TMP201));
				}
				LA9: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, tiger_104235)(TY102013* s) {
	NimStringDesc* result;
	TY102013* res;
	nimfr("tiger", "tiger.nim")
	result = 0;
	nimln(248, "tiger.nim");
	res = tigerbytes_103924(s);
	nimln(249, "tiger.nim");
	result = copyString(((NimStringDesc*) &TMP193));
	{
		NU8 i_104251;
		NI i_104257;
		NI L_104259;
		i_104251 = 0;
		nimln(3085, "system.nim");
		i_104257 = ((NI) 0);
		nimln(3086, "system.nim");
		L_104259 = (res ? res->Sup.len : 0);
		{
			nimln(3087, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				NimStringDesc* LOC5;
				NimStringDesc* LOC6;
				NI TMP202;
				if (!(i_104257 < L_104259)) goto LA3;
				nimln(3088, "system.nim");
				if ((NU)(i_104257) >= (NU)(res->Sup.len)) raiseIndexError();
				i_104251 = res->data[i_104257];
				nimln(251, "tiger.nim");
				LOC4 = 0;
				LOC5 = 0;
				LOC5 = nsuToHex(((NI64) (((NI) (i_104251)))), ((NI) 2));
				LOC6 = 0;
				LOC6 = nsuToLowerStr(LOC5);
				LOC4 = rawNewString(LOC6->Sup.len + result->Sup.len + 0);
appendString(LOC4, LOC6);
appendString(LOC4, result);
				result = LOC4;
				nimln(3089, "system.nim");
				TMP202 = addInt(i_104257, ((NI) 1));
				i_104257 = (NI)(TMP202);
				nimln(3090, "system.nim");
				{
					if (!!(((res ? res->Sup.len : 0) == L_104259))) goto LA9;
					failedassertimpl_86189(((NimStringDesc*) &TMP201));
				}
				LA9: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	HEX00_sboxesDatInit();
	stdlib_unsignedDatInit();
	HEX00_compressDatInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	tigerDatInit();
	HEX00_sboxesInit();
	stdlib_unsignedInit();
	HEX00_compressInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	tigerInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, tigerInit)(void) {
	NimStringDesc* LOC1;
	nimfr("tiger", "tiger.nim")
	nimln(253, "tiger.nim");
	LOC1 = 0;
	LOC1 = tiger_104071(NIM_NIL);
	printf("%s\015\012", LOC1? (LOC1)->data:"nil");
	nimln(255, "tiger.nim");
	{
		NimStringDesc* LOC4;
		LOC4 = 0;
		LOC4 = tiger_104071(((NimStringDesc*) &TMP203));
		if (!!(eqStrings(LOC4, ((NimStringDesc*) &TMP204)))) goto LA5;
		failedassertimpl_86189(((NimStringDesc*) &TMP205));
	}
	LA5: ;
	nimln(258, "tiger.nim");
	{
		NimStringDesc* LOC9;
		LOC9 = 0;
		LOC9 = tiger_104071(((NimStringDesc*) &TMP193));
		if (!!(eqStrings(LOC9, ((NimStringDesc*) &TMP206)))) goto LA10;
		failedassertimpl_86189(((NimStringDesc*) &TMP207));
	}
	LA10: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, tigerDatInit)(void) {
NTI102013.size = sizeof(TY102013*);
NTI102013.kind = 24;
NTI102013.base = (&NTI3405);
NTI102013.flags = 2;
NTI102013.marker = TMP151;
NTI102016.size = sizeof(TY102016*);
NTI102016.kind = 24;
NTI102016.base = (&NTI126);
NTI102016.flags = 2;
NTI102016.marker = TMP152;
}

